### ISSUE TITLE
Nameless API Returning Error Code 6

### ISSUE THREAD

**Issue by ThianFrietpan** [NamelessMC/Nameless-Plugin#102]
Hi. I have a nameless forum with version 2.0 pre-8. I'd like to use the NamelessMC spigot plugin. I want the players to register in Minecraft to prevent fake accounts on the forum, but the plugin returns Error Code 6 every time I request or send data.
This is the error:

[14:21:25 INFO]: NamelessAPI > Making userInfo request (GET
[14:21:25 INFO]: NamelessAPI > URL: https://legionmc.org/index.php?route=/api/v2/3tgjA1WUYi9lhqy52nkwXG0esIfmzFEB/userInfo&uuid=195a5f9e-18b9-4c97-8d6a-4ba5aaf14333
[14:21:25 INFO]: NamelessAPI > Parameters: uuid=195a5f9e-18b9-4c97-8d6a-4ba5aaf14333
[14:21:25 INFO]: NamelessAPI > Making register request (POST
[14:21:25 INFO]: NamelessAPI > URL: https://legionmc.org/index.php?route=/api/v2/3tgjA1WUYi9lhqy52nkwXG0esIfmzFEB/register
[14:21:25 INFO]: NamelessAPI > Parameters: uuid=195a5f9e-18b9-4c97-8d6a-4ba5aaf14333&email=thianfrietpan%40gmail.com&username=ThianFrietpan
[14:21:25 WARN]: com.namelessmc.NamelessAPI.ApiError: An API error occured with error code 6
[14:21:25 WARN]:        at com.namelessmc.NamelessAPI.NamelessPlayer.register(NamelessPlayer.java:252)
[14:21:25 WARN]:        at com.namelessmc.plugin.spigot.commands.RegisterCommand.lambda$0(RegisterCommand.java:53)
[14:21:25 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[14:21:25 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:21:25 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:21:25 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:21:25 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:21:25 WARN]:        at java.lang.Thread.run(Thread.java:748)

I hope that someone can help me. Thanks on advance.

**Comment by Derkades** [comment]
This is fixed in pr9 which will be released today

**Comment by ThianFrietpan** [comment]
Okay thanks for the really fast support xD
