### ISSUE TITLE
Error code 6 with API comm

### ISSUE THREAD

**Issue by DJIronic** [NamelessMC/Nameless-Plugin#106]
Hello, I just installed the plugin on all of my servers (bungee network) and I am fighting with this warn spamming theri chats:

```
[19:29:38 WARN]: com.namelessmc.NamelessAPI.ApiError: An API error occured with error code 6
[19:29:38 WARN]:        at com.namelessmc.NamelessAPI.NamelessAPI.submitServerInfo(NamelessAPI.java:118)
[19:29:38 WARN]:        at com.namelessmc.plugin.spigot.ServerDataSender.lambda$1(ServerDataSender.java:78)
[19:29:38 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[19:29:38 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:29:38 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:29:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[19:29:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[19:29:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```
the API URL was copied from the panel (running pre9). Any ideas?

**Comment by Derkades** [comment]
The API in pr9 used by the Spigot plugin has some issues. Until the next version is released, you can fix them manually.
1. Download and extract https://github.com/NamelessMC/Nameless/archive/v2.zip
2. Copy the contents in the `modules/Core/includes/endpoints` directory to the same directory on your website (overwriting existing files).
