### ISSUE TITLE
Error code 25 keeps coming cant fix

### ISSUE THREAD

**Issue by Allualbert** [NamelessMC/Nameless-Plugin#111]
Here's the console:

[12:27:58 INFO]: Making connection POST to url https://stormmc.net/index.php?route=/api/v2/**API_KEY_REMOVED**/serverInfo
[12:27:58 INFO]: Using User-Agent 'Nameless-Plugin'
[12:27:58 INFO]: Post body below
[12:27:58 INFO]: -----------------
[12:27:58 INFO]: {"tps":20,"time":1611145678383,"free-memory":600992688,"max-memory":6681526272,"allocated-memory":2036334592,"server-id":7,"groups":["Senior Mod","Mod","Tester","Admin","Junior Dev","Media","Member","Donor","Developer","Helper","Voidness","Head Dev","Builder","SUDO","Gambler","VIP","Junior Mod","Owner","MegaDonor","Manager","Head Admin","Director","Trial Mod","Hired Help","LonelyWanderer","Supervisor","HeroVIP","Network Manager"],"players":{}}
[12:27:58 INFO]: -----------------
[12:27:58 INFO]: Website response below
[12:27:58 INFO]: -----------------
[12:27:58 INFO]: {
[12:27:58 INFO]:     "error": true,
[12:27:58 INFO]:     "code": 25,
[12:27:58 INFO]:     "message": "Unable to update server info",
[12:27:58 INFO]:     "meta": null
[12:27:58 INFO]: }
[12:27:58 INFO]: -----------------
[12:27:58 WARN]: com.namelessmc.spigot.lib.nameless_api.ApiError: An API error occured with error code 25
[12:27:58 WARN]:        at com.namelessmc.spigot.lib.nameless_api.RequestHandler.makeConnection(RequestHandler.java:164)
[12:27:58 WARN]:        at com.namelessmc.spigot.lib.nameless_api.RequestHandler.post(RequestHandler.java:53)
[12:27:58 WARN]:        at com.namelessmc.spigot.lib.nameless_api.NamelessAPI.submitServerInfo(NamelessAPI.java:144)
[12:27:58 WARN]:        at com.namelessmc.spigot.ServerDataSender.lambda$run$1(ServerDataSender.java:106)
[12:27:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[12:27:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:27:58 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:27:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:27:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:27:58 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Derkades** [comment]
To disable group sync, set server id to 0

See https://github.com/NamelessMC/Nameless/issues/2036
