### ISSUE TITLE
new problem with velocity

### ISSUE THREAD

**Issue by Khikki** [NamelessMC/Nameless-Plugin#257]
```[06:54:23 ERROR]: Exception in task com.namelessmc.plugin.common.ApiProvider$$Lambda$984/0x0000000800fdce18@1a069881 by plugin NamelessMC
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
        at com.namelessmc.plugin.lib.nameless-api.Website.<init>(Website.java:45) ~[?:?]
        at com.namelessmc.plugin.lib.nameless-api.NamelessAPI.getWebsite(NamelessAPI.java:83) ~[?:?]
        at com.namelessmc.plugin.common.ApiProvider.api(ApiProvider.java:94) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
> 
```

_Originally posted by @Khikki in https://github.com/NamelessMC/Nameless-Plugin/issues/254#issuecomment-1126657556_

**Comment by Derkades** [comment]
Your website is not sending the "locale" in the json response, this was added a couple weeks ago. Please note that the development version of the plugin is only compatible with the latest development version of NamelessMC

**Comment by Khikki** [comment]
Can you tell me how can I install the latest version of nameless?

**Comment by Derkades** [comment]
Development releases can be downloaded from https://ci.rkslot.nl/view/NamelessMC/job/Nameless/ **these should not be used for anything other than testing purposes. Upgrades are not supported, frequent reinstallations are required**

**Comment by Khikki** [comment]
I tried to install my theme and module in the new version for test, otherwise localization will be called?

https://debug.namelessmc.com/s4lylEhoPK

**Comment by Derkades** [comment]
Templates and modules made for pr12 are very likely incompatible with the development version. In this case it looks like it is missing files for the new language system

**Comment by Derkades** [comment]
I'll close this issue since it seems to be resolved
