### ISSUE TITLE
Exception encountered when loading plugin: NamelessMC

### ISSUE THREAD

**Issue by Johno95CZ** [NamelessMC/Nameless-Plugin#280]
Exception encountered when loading plugin: NamelessMC
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.composer.Composer.<init>(org.yaml.snakeyaml.parser.Parser, org.yaml.snakeyaml.resolver.Resolver, org.yaml.snakeyaml.LoaderOptions)'
    at com.namelessmc.plugin.lib.configurate.yaml.ConfigurateYaml.loadConfigurate(ConfigurateYaml.java:37)
    at com.namelessmc.plugin.lib.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:158)
    at com.namelessmc.plugin.lib.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:42)
    at com.namelessmc.plugin.lib.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:155)
    at com.namelessmc.plugin.lib.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63)
    at com.namelessmc.plugin.lib.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56)
    at com.namelessmc.plugin.common.ConfigurationHandler.copyFromJarAndLoad(ConfigurationHandler.java:73)
    at com.namelessmc.plugin.common.ConfigurationHandler.load(ConfigurationHandler.java:63)
    at com.namelessmc.plugin.common.NamelessPlugin.load(NamelessPlugin.java:148)
    at com.namelessmc.plugin.bungee.BungeeNamelessPlugin.onEnable(BungeeNamelessPlugin.java:32)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:252)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:450)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:32)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

-----------------------
Only created folder and commands.yml... Nothing working

**Comment by supercrafter100** [comment]
Which plugin jar are you using?

**Comment by Johno95CZ** [comment]
Oh sorry, I forgot to write that I'm using plugin for bungee 3.0.3

**Comment by Derkades** [comment]
What's your bungeecord version? Perhaps it's an outdated version that we don't support. If it is a recent version, this would be a plugin bug

**Comment by Johno95CZ** [comment]
It's latest Aegis (v9.3.0 normal) fork for bungeecord, working with mc versions 1.7-1.19*

**Comment by Johno95CZ** [comment]
> 

It's just a fork for security... Every bungee plugin is working on it.

**Comment by Derkades** [comment]
It is not open source so I can only speculate... maybe it uses an outdated version of SnakeYAML, compared to BungeeCord? Of course, it could still be a plugin bug but I don't expect that to be the case since many people are using the plugin without issue

**Comment by Johno95CZ** [comment]
Okay, I will write to support of this fork if they can tell me details if they use the current version of SnakeYAML
