### ISSUE TITLE
[NamelessMC]: Cannot connect to your website, got an unexpected API error: API error nameless:invalid_post_contents (meta: {"field":"tps"}).

### ISSUE THREAD

**Issue by IkiaeM** [NamelessMC/Nameless-Plugin#281]
Bungee server

I have this error in the console (spam)
`[NamelessMC]: Cannot connect to your website, got an unexpected API error: API error nameless:invalid_post_contents (meta: {"field":"tps"}). Run /nlpl last_error to retrieve the full stack trace.`

Last_error :
```
[NamelessMC]: com.namelessmc.plugin.lib.nameless-api.exception.ApiException: API error nameless:invalid_post_contents (meta: {"field":"tps"})
        at com.namelessmc.plugin.lib.nameless-api.RequestHandler.makeConnection(RequestHandler.java:222)
        at com.namelessmc.plugin.lib.nameless-api.RequestHandler.post(RequestHandler.java:59)
        at com.namelessmc.plugin.lib.nameless-api.NamelessAPI.submitServerInfo(NamelessAPI.java:86)
        at com.namelessmc.plugin.common.AbstractDataSender.lambda$run$3(AbstractDataSender.java:158)
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
``` 
Debug info :
```
[NamelessMC]: [Nameless-Java-API Debug] Making connection POST to https://domaine.com/index.php?route=/api/v2/minecraft/server-info
[NamelessMC]: [Nameless-Java-API Debug] POST request body:
{"server-id":1,"time":xxx8876849xxx,"free-memory":xx38817xx,"max-memory":xx68709xx,"allocated-memory":536870912,"verify_command":"verify","players":{"xxxxx611be4048xxxfb642f330xxxxx":{"name":"USERNAME","login-time":xxx8876848xxx,"address":"/xxx.xxx.xxx.xxx:x546x"}}}
[23:07:29 INFO] [NamelessMC]: [Nameless-Java-API Debug] Website response body, after 116ms:
{
    "error": "nameless:invalid_post_contents",
    "meta": {
        "field": "tps"
    }
}
```

All commands work, user verification works. The problem comes from the minecraft server sending information to the site but it still does it even if I set "send-data-server" to `false`.

**Comment by supercrafter100** [comment]
Replace the contents of `modules/core/includes/endpoints/ServerInfoEndpoint.php` with this https://paste.rkslot.nl/raw/xayotubuwe

**Comment by IkiaeM** [comment]
Thanks :)
