### ISSUE TITLE
Update 1.20.1

### ISSUE THREAD

**Issue by Kub1sEej** [NamelessMC/Nameless-Plugin#348]
Hello!

Can you please update plugin tu support 1.20.1? When i write command "nlpl reload" console send me this message:

[10:41:52 WARN]: Unexpected exception while parsing console command "nlpl reload"
org.bukkit.command.CommandException: Unhandled exception executing 'nlpl reload' in com.namelessmc.plugin.bukkit.BukkitCommandProxy$SpigotCommand(nlpl)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1021) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:984) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:541) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:248) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:189) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:158) ~[purpur-1.20.1.jar:git-Purpur-2030]
        at com.namelessmc.plugin.bukkit.BukkitScheduler.runAsync(BukkitScheduler.java:21) ~[Nameless-Plugin-Paper-3.4.0.jar:?]
        at com.namelessmc.plugin.common.ApiProvider.load(ApiProvider.java:81) ~[Nameless-Plugin-Paper-3.4.0.jar:?]
        at com.namelessmc.plugin.common.NamelessPlugin.load(NamelessPlugin.java:144) ~[Nameless-Plugin-Paper-3.4.0.jar:?]
        at com.namelessmc.plugin.common.command.NamelessPluginCommand.execute(NamelessPluginCommand.java:40) ~[Nameless-Plugin-Paper-3.4.0.jar:?]
        at com.namelessmc.plugin.common.command.CommonCommand.verifyPermissionThenExecute(CommonCommand.java:86) ~[Nameless-Plugin-Paper-3.4.0.jar:?]
        at com.namelessmc.plugin.bukkit.BukkitCommandProxy$SpigotCommand.execute(BukkitCommandProxy.java:80) ~[Nameless-Plugin-Paper-3.4.0.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 8 more

**Comment by Derkades** [comment]
The plugin appears to be disabled. Did you use a plugin manager? Did you use /reload? Is there an error at startup that prevented the plugin from loading?

**Comment by Kub1sEej** [comment]
Plugin is online. And yes, i'm using plugin manager. /reload i cant use, because other plugins is not comfortable to /reload. This is solved, i guess. But now say this to me: https://pastebin.com/2cpx3uJj

**Comment by Derkades** [comment]
The API URL does not appear to be valid, as it returns a 404
