### ISSUE TITLE
[NamelessMC] com.namelessmc.plugin.lib.nameless-api.exception.NamelessException: Network connection error (not a Nameless issue). SSLHandshakeException: Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by HDAndreasEST** [NamelessMC/Nameless-Plugin#349]
at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.nameless-api.RequestHandler.makeConnection(RequestHandler.java:170)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.nameless-api.RequestHandler.get(RequestHandler.java:86)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.nameless-api.NamelessAPI.website(NamelessAPI.java:120)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.common.ApiProvider.api(ApiProvider.java:118)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.common.UserCache.lambda$update$0(UserCache.java:45)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
        at java.base/jdk.internal.reflect.GeneratedConstructorAccessor124.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.internal.Utils.tryCloneThrowable(Utils.java:142)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.internal.Utils.rethrowAsyncThrowable(Utils.java:104)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.internal.Utils.block(Utils.java:171)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.Methanol$HeadersTimeoutInterceptor.intercept(Methanol.java:993)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.Methanol$InterceptorChain.forward(Methanol.java:833)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.Methanol$AutoDecompressingInterceptor.intercept(Methanol.java:937)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.Methanol$InterceptorChain.forward(Methanol.java:833)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.Methanol$RequestRewritingInterceptor.intercept(Methanol.java:881)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.Methanol$InterceptorChain.forward(Methanol.java:833)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.methanol.Methanol.send(Methanol.java:316)
        at Nameless-Plugin-Spigot-3.4.0.jar//com.namelessmc.plugin.lib.nameless-api.RequestHandler.makeConnection(RequestHandler.java:133)
        ... 10 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
        at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.unwrapBuffer(SSLFlowDelegate.java:529)
        at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:433)
        at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:268)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
        ... 3 more

**Comment by Derkades** [comment]
Is your website TLS1.3-only? There have been reports of TLS 1.3 issues even though we enable TLS 1.3 support
