### ISSUE TITLE
v1.21.1 support?

### ISSUE THREAD

**Issue by mauvehed** [NamelessMC/Nameless-Plugin#397]
I'm new to Nameless (it is AMAZING!), however, I am running the latest Minecraft which is 1.21.1. The only plugin I can find appears to be for 1.20. Is there any expectation of this being updated?

I'll provide the error I am receiving on 1.21.1 in case there's another issue going on.

```
12:20:25 Starting minecraft server version 1.21.1
Loading properties
This server is running CraftBukkit version 4306-Spigot-a759b62-bd8aded (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Server Ping Player Sample Count: 12
Using 4 threads for Netty based IO
Debug logging is disabled
Default game type: SURVIVAL
Generating keypair
Starting Minecraft server on 0.0.0.0:2566
12:20:26
Using epoll channel type
Server thread/ERROR12:20:26
Could not load 'plugins/59032-v544056__NamelessPluginforv2.jar'
Console12:20:26
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:464) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4306-Spigot-a759b62-bd8aded]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4306-Spigot-a759b62-bd8aded]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4306-Spigot-a759b62-bd8aded]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4306-Spigot-a759b62-bd8aded]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 8 more
```

**Comment by supercrafter100** [comment]
Where did you download the plugin from? The name does not look right. Try downloading the latest build from here: https://ci.rkslot.nl/view/NamelessMC/job/Nameless%20Plugin/

**Comment by Derkades** [comment]
Whatever you have downloaded is indeed not the correct plugin jar file. Did you perhaps rename the zip file, containing multiple jar files, to .jar?

**Comment by mauvehed** [comment]
I found that file directly from your own docs

https://docs.namelessmc.com/en/faq

See the "Where can I download the NamelessMC plugin" header.

**Comment by mauvehed** [comment]
> Where did you download the plugin from? The name does not look right. Try downloading the latest build from here: https://ci.rkslot.nl/view/NamelessMC/job/Nameless%20Plugin/

I will retest with one from there. Thanks!

**Comment by mauvehed** [comment]
It works great, thank you kindly!
