### ISSUE TITLE
Error at BungeeCord login

### ISSUE THREAD

**Issue by ianfe9** [NamelessMC/Nameless-Plugin#44]
Hello, I have a problem when I join at BungeeCord with all my configured plugin, 1.8

[SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@623e088f, id=12, owner=com.namelessmc.plugin.NamelessBungee.NamelessPlugin@5c83ae01, task=com.namelessmc.plugin.NamelessBungee.player.PlayerEventListener$$Lambda$76/179327141@4ba7096, delay=0, period=0, running=true) encountered an exception
[01:39:43/INFO]: [Proxy-1] java.lang.NullPointerException
[01:39:43/INFO]: [Proxy-1]     at com.namelessmc.NamelessAPI.NamelessPlayer.init(NamelessPlayer.java:64)
[01:39:43/INFO]: [Proxy-1]     at com.namelessmc.NamelessAPI.NamelessPlayer.<init>(NamelessPlayer.java:39)
[01:39:43/INFO]: [Proxy-1]     at com.namelessmc.plugin.NamelessBungee.player.PlayerEventListener.lambda$onPlayerJoin$0(PlayerEventListener.java:27)
[01:39:43/INFO]: [Proxy-1]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
[01:39:43/INFO]: [Proxy-1]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[01:39:43/INFO]: [Proxy-1]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[01:39:43/INFO]: [Proxy-1]     at java.lang.Thread.run(Thread.java:748)

**Comment by IsS127** [comment]
Thanks for reporting this bug, but please install from spigot instead.
The current source code is not tested

**Comment by ianfe9** [comment]
I have another error with Spigot version

[02:15:41 WARN]: org.apache.commons.lang.UnhandledException: Plugin NamelessMC v@project.version@ generated an exception while executing task 416
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.namelessmc.NamelessAPI.NamelessPlayer.init(NamelessPlayer.java:64)
        at com.namelessmc.NamelessAPI.NamelessPlayer.<init>(NamelessPlayer.java:39)
        at com.namelessmc.plugin.NamelessSpigot.player.PlayerEventListener.lambda$onPlayerJoin$0(PlayerEventListener.java:28)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

I compiled the spigot version

**Comment by Derkades** [comment]
Fixed a few days ago
