### ISSUE TITLE
API key 

### ISSUE THREAD

**Issue by hamodi1299-Ignite-hamodi1299** [NamelessMC/Nameless-Plugin#64]
# Template,
* What kind of issue is it? (question, bug, suggestion, etc.)
* In which Minecraft Server Software did it occur, Spigot or BungeeCord?
* In which version did it occur? If it's a jenkins build, tell us the build number.
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?

# PLEASE UPLOAD IMAGES TO IMGUR OR ANY OTHER IMAGE UPLOADER WEBSITE!
# PLEASE UPLOAD LOGS TO HASTEBIN.COM!

### What kind of issue is it? (question, bug, suggestion, etc.)
I copied the API key from the website but when I put it on the config file on my server it says that there no API key like that :(

### In which Minecraft Server Software did this occur?
Waterfall and Paperspigot 

### In which version did it occur?
Pre release 1

### How would you describe the issue?
the API key not working

### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?

> [20:19:17 INFO]: [NamelessMC] [WARNING] Invalid API key
> [20:19:17 WARN]: java.net.MalformedURLException: no protocol: jhpWO0VIqZlxKNTiE49Guwb8svDBzg2U/checkConnection
> [20:19:17 WARN]: at java.net.URL.<init>(URL.java:593)
> [20:19:17 WARN]: at java.net.URL.<init>(URL.java:490)
> [20:19:17 WARN]: at java.net.URL.<init>(URL.java:439)
> [20:19:17 WARN]: at com.namelessmc.namelessplugin.spigot.API.CheckWebAPIConnection.<init>(CheckWebAPIConnection.java:28)
> [20:19:17 WARN]: at com.namelessmc.namelessplugin.spigot.API.NamelessAPI.checkConnection(NamelessAPI.java:46)
> [20:19:17 WARN]: at com.namelessmc.namelessplugin.spigot.API.Config.NamelessConfigManager.initConfig(NamelessConfigManager.java:89)
> [20:19:17 WARN]: at com.namelessmc.namelessplugin.spigot.API.Config.NamelessConfigManager.initializeFiles(NamelessConfigManager.java:27)
> [20:19:17 WARN]: at com.namelessmc.namelessplugin.spigot.NamelessPlugin.onEnable(NamelessPlugin.java:105)
> [20:19:17 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> [20:19:17 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
> [20:19:17 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
> [20:19:17 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
> [20:19:17 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
> [20:19:17 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
> [20:19:17 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
> [20:19:17 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
> [20:19:17 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
> [20:19:17 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
> [20:19:17 WARN]: at java.lang.Thread.run(Thread.java:748)
> [20:19:17 INFO]: [NamelessMC] [WARNING] Invalid API Url/Key, Please set the correct API url! disabling features
> [20:19:17 INFO]: [NamelessMC] Disabling NamelessMC vPre-1.1.0
> [20:19:18 INFO]: [NamelessMC] [Info] Found no new updates!

**Comment by Derkades** [comment]
You need to set the API URL in the config, not the api key

**Comment by partydragen** [comment]
@hamodi1299-Ignite-hamodi1299 Please reset your api key if you don't have did it yet, As you have leaked your secret key

**Comment by Derkades** [comment]
Closing because no activity
