### ISSUE TITLE
Bungee load errros, help me pls

### ISSUE THREAD

**Issue by cristianrg36** [NamelessMC/Nameless-Plugin#79]
[15:32:14 WARN]: Error enabling plugin NamelessMC
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_242]
at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_242]
at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_242]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_242]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_242]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:362) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:270) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
... 18 more

IN BUNGEECORD

**Comment by samerton** [comment]
The Nameless plugin for v2 is for Spigot only, you can install it on each of your Spigot servers.
