### ISSUE TITLE
NamelessAPI > Response: {"error": true, "code": 6, "message": "Invalid POST contents"}

### ISSUE THREAD

**Issue by edgcumt** [NamelessMC/Nameless-Plugin#97]
First thing apologies for the template add. Smashing console commands without realising which window was selected.

basically im getting this particular error in the minecraft console from the NamelessMC plugin : -

[16:36:25] [Craft Scheduler Thread - 205/INFO]: NamelessAPI > Making serverInfo request (POST
[16:36:25] [Craft Scheduler Thread - 205/INFO]: NamelessAPI > URL: http://example.ddns.net/Nameless/index.php?route=/api/v2/mrjgI4HyNMJLCphPbUtG7e6zFl291Wk5/serverInfo
[16:36:25] [Craft Scheduler Thread - 205/INFO]: NamelessAPI > Parameters: info=%7B%22max-memory%22%3A960167936%2C%22tps%22%3A20%2C%22players%22%3A%7B%7D%2C%22free-memory%22%3A740843024%2C%22time%22%3A1605717385151%2C%22allocated-memory%22%3A960167936%2C%22server-id%22%3A1%7D
[16:36:26] [Craft Scheduler Thread - 205/INFO]: NamelessAPI > Response: {    "error": true,    "code": 6,    "message": "Invalid POST contents"}
[16:36:26] [Craft Scheduler Thread - 205/WARN]: com.namelessmc.NamelessAPI.ApiError: An API error occured with error code 6
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at com.namelessmc.NamelessAPI.NamelessAPI.submitServerInfo(NamelessAPI.java:118)
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at com.namelessmc.plugin.spigot.ServerDataSender.lambda$1(ServerDataSender.java:78)
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[16:36:26] [Craft Scheduler Thread - 205/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)

I am using NamelessMC version 2.0.0-pre7 with the Nameless minecraft plugin version  v2 beta-32. I have a server integration setup on the site with the server id and api url in the NamelessMC plugin config.yml file all set. as to have the plugin send server status info to the status page of the nameless website,

One of the things i am curious about is if the minecraft server plugin is safe to work with the paperclip server .jar. as i am using the latest paperMC build 283 .jar and assuming it was mostly a spigot clone, i was hoping it would work like it is a spigot. please advise me if this is incorrect.
 - I am also curious if it is necessary to set up https and friendly urls for the mc server plugin to work? 
 - For the time being im hosting through a no-ip DynDNS using example.ddns.net and have the nameless MC directory 
   installed at /var/www/html/Nameless on an apache2 service. Could either of these setups be interfering with the plugin?
sorry if these are noobish or unnecessary questions. i have only self educated skills with web hosting and am still very inexperienced.

I have turned on debug mode in the settings and have attempted the help at the "plugin-is-not-working" page on the wiki.
when using the api url in the browser i get 

{
    "error": true,
    "code": 3,
    "message": "Invalid API method"
}

According to the help page this says something is working somewhere and i feel very close to getting it to work.
a similar error is also displayed in the console from the debug output when it queries the server but with code 3 - Invalid POST contents as shown from the console info/warnings at top of this post.

also when inputting "http://example.ddns.net/Nameless/index.php?route=/api/v2/myAPIkey/info" into browser url it returns 

{
    "nameless_version": "2.0.0-pr7",
    "language": "EnglishUK",
    "version_update": {
        "update": false
    },
    "modules": [
        "Core",
        "Forum"
    ],
    "error": false
}

I guess this issue would be a question as to weather it is my setup, or a lacking of, that is causing this issue. unless someone can advise me that either ssl/dyndns/nameless-directory-path is causing this problem then i guess it is a bug.

I have also found a closed issue from 2019 with the same error code and a mention of : -

"following are reasons why the API would be returning an error code 6:
 - post request is empty or the object isn't named 'info'
 - server-id, max-memory, free-memory, allocated-memory, tps, players aren't set"

There was no mention on how to rename object or set max-mem, free-mem etc but there was a mention about a friendly url issue at last post but i found removing the http:// at the beginning of the API url through a syntax error and did not solve my problem even though the issue was closed at this post. 

[https://github.com/NamelessMC/Nameless-Plugin/issues/68](url)

as mentioned eirlier this was on latest stable build of PaperMC-283 and accured in version 1.0.0-pre-7

I am still to setup https before attempting more with the minecraft plugin but i have been at it for hours now so am going to leave it be for a few days before returning to it.
I look foward to hearing your suggestions on this issue as to help guide me to achieve "valid POST contents" with my NamelessAPI responces 

All the best
 Tobias Edgcumbe

**Comment by Derkades** [comment]
Does your website use https:// or http://?

**Comment by edgcumt** [comment]
so far it is only using http:// but over the weekend or next week i am going to get on with setting it up to use https://

will it only work with https://?

**Comment by Derkades** [comment]
No, just checking if your API URL was correct. I do not know what causes this issue and I can't really fix it, pr8 has a completely new API. All you can do right now is wait for the pr8 release (couple weeks?). It should work then, if it doesn't I'll be able to investigate

**Comment by edgcumt** [comment]
oh nice. That is great news to hear about the pr8 release. I look forward to updating to the new version.
In the meantime i will close this issue and wait for the new release before trying to utilize this feature again.
Thank you for your help. It's been very useful to decide where to go from here.
